name: Rebase

on:
  schedule:
    - cron: '0 23 * * *'

jobs:
  build:
    name: Automatic rebase
    runs-on: ubuntu-20.04
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install git
    - name: Rebase
      run: |
        git config --global user.name "${GITHUB_USER}"
        git config --global user.email "${GITHUB_EMAIL}"
        git clone https://"${GITHUB_USER}":"${GITHUB_TOKEN}"@github.com/droid-legacy/android_frameworks_native-1.git -b 12.1
        cd android_frameworks_native-1
        git fetch https://github.com/crdroidandroid/android_frameworks_native.git 12.1
        git rebase FETCH_HEAD
        git push -f
      env:
        GITHUB_EMAIL: ${{ secrets.EMAIL }}
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        GITHUB_USER: ${{ secrets.USERNAME }}
